/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wbitoolkit_rna_MfeFold */

#ifndef _Included_wbitoolkit_rna_MfeFold
#define _Included_wbitoolkit_rna_MfeFold
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wbitoolkit_rna_MfeFold
 * Method:    fold
 * Signature: (Ljava/lang/String;F)F
 */
JNIEXPORT jfloat JNICALL Java_wbitoolkit_rna_MfeFold_fold
  (JNIEnv *, jobject, jstring, jfloat);

#ifdef __cplusplus
}
#endif
#endif
