/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmipara2_MfeFold */

#ifndef _Included_jmipara2_MfeFold
#define _Included_jmipara2_MfeFold
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmipara2_MfeFold
 * Method:    fold
 * Signature: (Ljava/lang/String;F)F
 */
JNIEXPORT jfloat JNICALL Java_jmipara2_MfeFold_fold
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     jmipara2_MfeFold
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmipara2_MfeFold_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
 