/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wbitoolkit_smooth_Loess */

#ifndef _Included_wbitoolkit_smooth_Loess
#define _Included_wbitoolkit_smooth_Loess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wbitoolkit_smooth_Loess
 * Method:    smooth
 * Signature: ([D[DDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_wbitoolkit_smooth_Loess_smooth
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
